### ISSUE TITLE
Missing mathchoice(?)

### ISSUE THREAD

**Issue by rgbkrk** [nteract/mathjax-electron#11]
<img width="800" alt="screen shot 2016-08-24 at 1 19 03 pm" src="https://cloud.githubusercontent.com/assets/836375/17946477/67bec01a-69fd-11e6-90f8-dcef139a7b15.png">

Originating source from Markdown:

```
$\begin{equation*}
P(E)   = {n \choose k} p^k (1-p)^{ n-k} 
\end{equation*}$
```

Are we missing a bundle for stats/probability/discrete math for `\choose`?

**Comment by rgbkrk** [comment]
Original notebook I loaded:

https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Typesetting%20Equations.ipynb

**Comment by rgbkrk** [comment]
Everything else on that page is super awesome.

**Comment by lgeiger** [comment]
Looks like I slimed down MathJax a bit too much. 😁
