### ISSUE TITLE
Required sourcemap?

### ISSUE THREAD

**Issue by nickzuber** [nteract/mathjax-electron#15]
Tried to use this in my project and was met with the following error:

```
Failed to parse SourceMap: http://localhost:8080/js/mathjax-electron.js.map
```

**Comment by rgbkrk** [comment]
How are you loading `mathjax-electron`?

**Comment by lgeiger** [comment]
@nickzuber Have you solved the problem? If not can you provide more information for us to figure out what's going on?

**Comment by nickzuber** [comment]
I may have tried to use this out of the context of Electron... 😄 Sorry guys my bad — everything should be working fine now!
