### ISSUE TITLE
Is it possible to run this offline?

### ISSUE THREAD

**Issue by JeremiahUL** [nteract/mathjax-electron#37]
I am using this in a electron-react offline application where user can turn off internet, 
It throws error "MathJax is not defined".

Code below: 
```
...
const { typesetMath } = require("mathjax-electron");
...

const text = String.raw`${html}`;
const container = document.createElement("div");
    container.innerHTML = text;
    const Final = typesetMath(container);
    return (
        <Final />
    )
```
I also added the script in the head tag as is in the docs.
What am I doing wrong?
And I wish to use this offline

**Comment by captainsafia** [comment]
The mathjax-electron package uses a built-in version of the MathJax library (see [here](https://github.com/nteract/mathjax-electron/tree/master/MathJax-2.7.5)) so it can run offline.

Do you have a repro project you can share for this issue?

**Comment by JeremiahUL** [comment]
How do I run it in react

**Comment by JeremiahUL** [comment]
With react and electron

**Comment by captainsafia** [comment]
@JeremiahUL I would recommend checking out how this package is used in the nteract desktop app. You can start by reading the code [here](https://github.com/nteract/nteract/blob/efee00f6f4498992073e1ff8b17e2037a4781999/applications/desktop/src/notebook/index.tsx).

**Comment by JeremiahUL** [comment]
I really appreciate this @captainsafia

**Comment by JeremiahUL** [comment]
import { mathJaxPath } from "mathjax-electron";
import * as MathJax from "@nteract/mathjax";
...
 return (
        <MathJax.Provider 
        src={mathJaxPath} 
        input="tex">
            <MathJax.Node>{`x^2 + y^2 = z^2`}</MathJax.Node>
        </MathJax.Provider>
    );
...
This throws a blank screen

**Comment by captainsafia** [comment]
@JeremiahUL Can you share a repro project?

**Comment by JeremiahUL** [comment]
https://github.com/jerryheir/rn-web-electron
Please clone this repo.
```yarn install```
```yarn start```
Open a new terminal
```yarn electron```

**Comment by JeremiahUL** [comment]
Hi @captainsafia Were you able to test this?

**Comment by JeremiahUL** [comment]
Hello here, Is there an issue with the implementation?

**Comment by JeremiahUL** [comment]
cc @smashwilson @ellisonbg @yuvipanda

**Comment by captainsafia** [comment]
@JeremiahUL Please avoid tagging folks who aren't active in the repo in this issue so that we are courteous of everyone's notifications.

As for the issue, it looks like you are building your application with react-native and don't have any Electron config in there. This package is only designed to work with Electron.

**Comment by JeremiahUL** [comment]
Thats an example repo. And it is react native web. It is similar to React
which is web. Please read about it. Secondly, I had a deadline and I had to
call for any help I could get quickly. I apologize for that. Thirdly, one
of our engineers had to build the mathjax offline feature from scratch and
we did not use this library anymore. Again, I apologize for any issues I
may have caused
