### ISSUE TITLE
Add example to readme

### ISSUE THREAD

**Issue by injectless** [nteract/mathjax-electron#4]
How can I use this? (without Jasmine, JSDOM or other dependences)
I'm currently using MathJax but as <script src="..">, with require(''); it gives me error..

**Comment by lgeiger** [comment]
You can install `mathjax-electron` with `npm install mathjax-electron`, Jasmine and JSDOM etc. are just development dependencies and aren't installed then.

Here is an example of mathjax-electron in use:
https://github.com/nteract/transformime/blob/master/src/latex.transform.js

**Comment by lgeiger** [comment]
@injectless Today we released version `1.0.0`. 
The README has now an example and a full API documentation.

**Comment by injectless** [comment]
I'll try out next week when I get home!
Amazing, wait for the feedback then! 
Thanks forever.

**Comment by injectless** [comment]
Thanks for this. I'd like to contribute with an Angular-Bind to the project.
```
 function LaTeXTransform(mimetype, value) {
   let latex = '$$' + value + '$$';
    var container = document.createElement('div');
    container.innerHTML = latex
    MathJaxx.loadAndTypeset(document, container,
      function() {
        container.getElementsByClassName('MathJax_SVG_Display');
        container.getElementsByClassName('MathJax_SVG');
        container.getElementsByTagName('script')[0].textContent;
      });
    return container;
}
    
// Directive. Call it: <MathJax></MathJax> or inside a div: <div MathJax>{{expression}}</div>
app.directive("MathJax", function() {
    return {
        restrict: "A",
        controller: ["$scope", "$element", "$attrs", function($scope, $element, $attrs) {
            $scope.$watch($attrs.mathjaxBind, function(value) {
                $element.html("");
                $element.append(LaTeXTransform('text/latex', value));
                
            });
        }]
    };
});
```

**Comment by injectless** [comment]
seems like you are familiar with MathJax, @lgeiger 
how can I convert that SVG to a PNG?

does it mathjax have such functionality?
i can work with SVG (for the angular binding thing), but i need that final expression to be a PNG string base64 :/

**Comment by lgeiger** [comment]
I think this kind of functionality shouldn't be inside `mathjax-electron`. For the actual LaTeX transform we use `mathjax-electron` in different contexts (e.g. [nteract](https://github.com/nteract/nteract/blob/master/src/notebook/components/latex.js) or [transformime](https://github.com/nteract/transformime/blob/master/src/latex.transform.js)). So I think `mathjax-electron` should only include functionality related to loading MathJax and triggering the typesetting. I would suggest making a new npm package for this.


> does it mathjax have such functionality?

I don't think so. But why would you like to convert to PNG?

**Comment by rgbkrk** [comment]
That's great @injectless!

It's true that we'll keep the scope of this package restricted to vanilla MathJax. Another repository and npm package for Angular bindings is fine, whether in your personal org or on nteract.

**Comment by injectless** [comment]
Mostly, I agree with you. This library doesn't have to export the SVG as PNG.
However.. try to print it in a PDF or any other format for that matter and see how SVG works.

That's why I need PDF. SVG won't work for me, and maybe for a lot of folks.
Any suggestions, @lgeiger ?
I tried converting in several ways but apparently I can't get it working. 
In mathjax-node they support this feature, tho I couldn't use the entire library in Electron.

**Comment by injectless** [comment]
https://github.com/injectless/mathjax-atom-directive

**Comment by lgeiger** [comment]
[This](https://github.com/mathjax/MathJax-node/blob/master/lib/mj-page.js#L805) is what `mathjax-node` is doing. Another way would be to use some other [MathJax output format](http://docs.mathjax.org/en/latest/output.html).

**Comment by injectless** [comment]
Funny, that's a pretty near approach of what I wrote.
Couldn't use it in Electron, it has dependences like jsdom, batik, and another ones that I don't really need to perform a job like this.

Damn.

**Comment by matikbird** [comment]
So, this is what I got:

![screenshot_2016-07-21_16-15-31](https://cloud.githubusercontent.com/assets/12424545/17035558/5fecf71c-4f5e-11e6-8032-1d4e91e07580.png)

## Ok.
So, now I when I press "**Agregar function**" button, the **SVG** is transformed to a **PNG** and it's append to a div**.**

```
 var nodes = document.getElementsByClassName("MathJax_SVG");
          var svg = nodes[0].getElementsByTagName("svg")[0];
            var w = svg.getAttribute("width"), h = svg.getAttribute("height");
          var css = svg.style.cssText+" width:"+w+"; height:"+h;
                    svg.style.cssText = ""; // this will be handled by the <img> tag instead
                    svg.setAttribute("xmlns","http://www.w3.org/2000/svg");
                    svg = [
                      '<?xml version="1.0" standalone="no"?>',
                      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
                      svg.outerHTML
                    ].join("\n"); 

              var canvas = document.createElement( "canvas" );
              var ctx = canvas.getContext( "2d" );
               
              var img = document.createElement( "img" );
              img.setAttribute( "src", "data:image/svg+xml;base64," + btoa(svg) );
               
              img.onload = function() {
                  ctx.drawImage( img, 0, 0 );
                  
                       var __id = $('#projectactual').html();
                       $("#"+__id).append(canvas.toDataURL( "image/png" ));
                                       $rootScope.$broadcast('appendmath', tab);
              };
```

That has to return me a PNG in base64 from the SVG, but the **img.onload** function seems to never fire.
Whaaaaaaaaaaaat is going on?!

**Comment by rgbkrk** [comment]
Since the image is generating dynamically, the `onload` property needs to be set _before_ you set `src` (so you don't miss the callback).

**Comment by matikbird** [comment]
Yes. I still need help about that, @rgbkrk @lgeiger 
I've putted the onload before this time, and it didn't work..
See if you can reproduce it yourself:
https://github.com/matikbird/textiled

**Comment by lgeiger** [comment]
I have never used Angular before but as Kyle suggested this this should work:
```javascript
 var nodes = document.getElementsByClassName("MathJax_SVG");
          var svg = nodes[0].getElementsByTagName("svg")[0];
            var w = svg.getAttribute("width"), h = svg.getAttribute("height");
          var css = svg.style.cssText+" width:"+w+"; height:"+h;
                    svg.style.cssText = ""; // this will be handled by the <img> tag instead
                    svg.setAttribute("xmlns","http://www.w3.org/2000/svg");
                    svg = [
                      '<?xml version="1.0" standalone="no"?>',
                      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
                      svg.outerHTML
                    ].join("\n"); 

              var canvas = document.createElement( "canvas" );
              var ctx = canvas.getContext( "2d" );

              var img = document.createElement( "img" );

              img.onload = function() {
                  ctx.drawImage( img, 0, 0 );

                       var __id = $('#projectactual').html();
                       $("#"+__id).append(canvas.toDataURL( "image/png" ));
                                       $rootScope.$broadcast('appendmath', tab);
              };
              img.setAttribute( "src", "data:image/svg+xml;base64," + btoa(svg) );
```

Though if I understand `$("#"+__id).append(canvas.toDataURL( "image/png" ));` correctly it only appends the dataUrl and not the actual image.

**Comment by matikbird** [comment]
That's the code it already has, it's not working.
You can try it out yourself with the repo I left below

**Comment by lgeiger** [comment]
> That's the code it already has, it's not working.

The code in the repo is:
```javascript
          img.onload = function() {
           var nodes = document.getElementsByClassName("MathJax_SVG");
          var svg = nodes[0].getElementsByTagName("svg")[0];
            var w = svg.getAttribute("width"), h = svg.getAttribute("height");
          var css = svg.style.cssText+" width:"+w+"; height:"+h;
                    svg.style.cssText = ""; // this will be handled by the <img> tag instead
                    svg.setAttribute("xmlns","http://www.w3.org/2000/svg");
                    svg = [
                      '<?xml version="1.0" standalone="no"?>',
                      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
                      svg.outerHTML
                    ].join("\n"); 

              var canvas = document.createElement( "canvas" );
              var ctx = canvas.getContext( "2d" );
               
              var imgq = document.createElement( "img" );
              imgq.setAttribute( "src", "data:image/svg+xml;base64," + btoa(svg) );
               
              
                  ctx.drawImage( imgq, 0, 0 );
                  
                       var __id = $('#projectactual').html();
                       $("#"+__id).append(canvas.toDataURL( "image/png" ));
                                       $rootScope.$broadcast('appendmath', tab);
              };
               $scope.closeDialog();
    };
```

That's not the same 😉
